#+TITLE: BNF Mode for GNU Emacs
#+AUTHOR: Serghei Iakovlev

[[https://www.gnu.org/licenses/gpl-3.0.txt][https://img.shields.io/badge/license-GPL_3-green.svg]]
[[https://travis-ci.com/sergeyklay/bnf-mode][https://travis-ci.com/sergeyklay/bnf-mode.svg]]

A GNU Emacs major mode for editing BNF grammars.

#+begin_quote
“Precise language is not the problem.  Clear language is the problem.”

Richard Feynman
#+end_quote

Currently provides basic syntax and font-locking for BNF files. BNF notation is
supported exactly form as it was first announced in the ALGOL 60 report.
EBNF and ABNF are not supported but  in my plans for the near future.

When developing this mode, the following documents were taken into account:

- [[https://www.masswerk.at/algol60/report.htm][Revised Report on the Algorithmic Language Algol 60]]
- [[https://tools.ietf.org/html/rfc822][RFC822]]: Standard for ARPA Internet Text Messages
- [[https://tools.ietf.org/html/rfc5234][RFC5234]]: Augmented BNF for Syntax Specifications: ABNF
- [[https://tools.ietf.org/html/rfc7405][RFC7405]]: Case-Sensitive String Support in ABNF

** Features

- Basic syntax definition
- Syntax highlighting

** Installation

Known to work with GNU Emacs 24.3 and later.  BNF Mode may work with
older versions of Emacs, or with other flavors of Emacs (e.g. XEmacs)
but this is /not/ guaranteed.  Bug reports for problems related to using
BNF Mode with older versions of Emacs will most like not be addressed.

The master of all the material is the Git repository at
https://github.com/sergeyklay/bnf-mode .

NOTE: The ~master~ branch will always contain the latest unstable version.
If you wish to check older versions or formal, tagged release, please switch
to the relevant [[https://github.com/sergeyklay/bnf-mode/tags][tag]].

*** Using use-package

TODO

*** Using MELPA

TODO

*** Manual Install

1. Download ~bnf-mode.el~
2. Put the file in your Elisp common folder like ~$HOME/.emacs.d/lisp/~
3. Then you can include like this:
   #+begin_src emacs-lisp
   (add-to-list 'load-path
                (expand-file-name "lisp" user-emacs-directory))
   #+end_src
4. Add /either/ of the two following lines to your initialization file.
   The first only loads BNF Mode when necessary, the 2nd always during startup
   of GNU Emacs.
   #+begin_src emacs-lisp
   (autoload 'bnf-mode "bnf-mode" nil t)
   ;; OR
   (require 'zephir-mode)
   #+end_src
5. Optionally byte compile ~bnf-mode.el~ for faster startup: ~M-x byte-compile~

** Usage

*** Interactive Commands

| Command (For the ~M-x~ prompt.) | Description                      |
|---------------------------------+----------------------------------|
| ~bnf-mode~                      | Switches to BNF Mode.            |
| ~bnf-mode-version~              | Print version info for BNF Mode. |

Any file that matches the glob ~*.bnf~ is automatically opened in ~bnf-mode~.

** Support

Feel free to ask question or make suggestions in our [[https://github.com/sergeyklay/bnf-mode/issues][issue tracker]] .

** Changes

To see what has changed in recent versions of BNF Mode, see the [[https://github.com/sergeyklay/bnf-mode/blob/master/CHANGELOG.org][CHANGELOG.org]] .

** External Links

- [[https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form][Wikipedia: Backus–Naur form]]
- [[https://en.wikipedia.org/wiki/Extended_Backus%25E2%2580%2593Naur_form][Wikipedia: Extended Backus–Naur form]]
- [[https://en.wikipedia.org/wiki/Augmented_Backus%25E2%2580%2593Naur_form][Wikipedia: Augmented Backus–Naur form]]
- [[https://www.cl.cam.ac.uk/~mgk25/iso-14977.pdf][ISO/IEC 14977: EBNF]]
- [[https://www.ics.uci.edu/~pattis/ICS-33/lectures/ebnf.pdf][EBNF: A Notation to Describe Syntax]]

** License

BNF Mode is open source software licensed under the [[https://github.com/sergeyklay/bnf-mode/blob/master/LICENSE][GNU General Public Licence version 3]] .
