# Copyright (C) 2019-2024 Free Software Foundation, Inc.
#
# License
#
# This file is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.

name: build

on:
  push:
    branches:
      # This is to make sure that there is no broken CI on
      # the default branch.
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "GNU Emacs ${{ matrix.emacs_version }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        emacs_version:
          # 2016-09 - 2017-09
          - '25.1'
          - '25.2'
          - '25.3'

          # 2018-05 - 2019-08
          - '26.1'
          - '26.2'
          - '26.3'

          # 2020-08 - 2021-03
          - '27.1'
          - '27.2'

          # 2022-04 - 2022-09
          - '28.1'
          - '28.2'

          # 2023-07 - 2024-06
          - '29.1'
          - '29.2'
          - '29.3'
          - '29.4'
          - snapshot
        include:
          - emacs_version: snapshot
            allow_failure: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Setup GNU Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/cache@v3
        id: cache-cask-packages
        with:
          path: .cask
          key: cask-packages-${{ matrix.emacs_version }}-${{ hashFiles('**/Cask') }}

      - uses: actions/cache@v3
        id: cache-cask-executable
        with:
          path: ~/.cask
          key: cask-executable-${{ matrix.emacs_version }}

      - name: Setup Cask
        uses: cask/setup-cask@master
        if: steps.cache-cask-executable.outputs.cache-hit != 'true'
        with:
          version: snapshot

      - name: Set Environment Variables
        run: |
          echo "$HOME/.cask/bin" >> $GITHUB_PATH
          if [ "${{ matrix.emacs_version }}" != "snapshot" ]; then
            echo UNDERCOVER_FORCE=1 >> $GITHUB_ENV
          fi

      - name: Fast Makefile Test
        run: make help

      - name: Initialize the Project
        if: steps.cache-cask-packages.outputs.cache-hit != 'true'
        run: make init

      - name: Byte Compile BNF Mode
        run: make build

      - name: Check for Errors in the Documentation
        run: make checkdoc

      - name: Run Unit Tests
        if: matrix.allow_failure != true
        run: make test

      - name: Run Unit Tests
        if: matrix.allow_failure == true
        run: 'make test || true'

      - name: After Success Reporting
        if: success()
        run: git log --format=fuller -5
